GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "abc",
  "author": "me",
  "url": "https://google.com",
  "likes": 100
}

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "admin",
  "password": "passw0rd123",
  "name": "I am the admin"
}