GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/1
###
DELETE http://localhost:3001/api/persons/2
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "hello",
    "number": "12345678"
}
###
PUT http://localhost:3001/api/persons/5e93259697cfc41575e6fa31
content-type: application/json

{
    "name": "hello",
    "number": "12345678"
}